# Generated by Django 4.1.2 on 2022-12-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='med_type',
            table='Med_type',
        ),
    ]
