# Generated by Django 4.1.2 on 2022-12-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0004_user_medicine_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_medicine',
            name='time2',
        ),
        migrations.AlterField(
            model_name='user_medicine',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
