# Generated by Django 4.1.2 on 2022-12-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taken_medicine',
            fields=[
                ('usermed_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='med_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
